version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:legacy

    ports:
      - "8080:8080"

    environment:
    
      KEYCLOAK_USER: admin

      KEYCLOAK_PASSWORD: admin

      DB_ADDR: database-1.ckhdkwvigsti.us-east-1.rds.amazonaws.com

      DB_USER: admin

      DB_PASSWORD: password

      DB_VENDOR: mysql
      
      DB_DATABASE: keycloak
      
      DB_PORT: 3306
      
      # JAVA_OPTS_APPEND: "-Djboss.as.management.blocking.timeout=7200"
      
      # JDBC_PARAMS: "connectTimeout=30000"
